version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: autoservice_postgres
    env_file:
      - .env
    ports:
      - "5434:5432"
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:10
    container_name: autoservice_flyway
    command: migrate
    env_file:
      - .env
    volumes:
      - ./flyway/sql:/flyway/sql
      - ./flyway/flyway.conf:/flyway/conf/flyway.conf
    depends_on:
      postgres:
        condition: service_healthy

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: autoservice_pg_exporter

    environment:
      DATA_SOURCE_NAME: ${DATA_SOURCE_NAME}
    volumes:
      - ./queries.yaml:/queries.yaml
    command:
      - "--extend.query-path=/queries.yaml"
      - "--collector.stat_statements"
    ports:
      - "9187:9187"
    depends_on:
      postgres:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    container_name: autoservice_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - postgres_exporter

  grafana:
    image: grafana/grafana
    container_name: autoservice_grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  postgres_data:
