flyway.url=${POSTGRES_URL}
flyway.user=${POSTGRES_USER}
flyway.password=${POSTGRES_PASSWORD}
flyway.locations=filesystem:/flyway/sql
flyway.baselineOnMigrate=true

flyway.placeholders.adminPassword=${ADMIN_PASSWORD}
flyway.placeholders.readonlyPassword=${READONLY_PASSWORD}
flyway.placeholders.appPassword=${APP_PASSWORD}